# Generated by Django 6.0.2 on 2026-02-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='habilidades/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
